### ISSUE TITLE
[request/suggestion] data-corset-props attr instead of many data-corset-prop-* attrs

### ISSUE THREAD

**Issue by JaneOri** [matthewp/corset#160]
Assuming the data-corset-prop-* attrs are there individually just for an internal query selector and not a deeper need, would you consider changing it to be all contained in one `data-corset-props` and use the [~= attr selector](https://developer.mozilla.org/en-US/docs/Web/CSS/Attribute_selectors#attrvalue_2) instead like `[data-corset-props~=--corset-prop]`

Current:
<img width="827" alt="image" src="https://user-images.githubusercontent.com/7545075/182042274-531b0fba-e9d6-409d-9635-b949ec242eae.png">

Proposed:
<img width="938" alt="image" src="https://user-images.githubusercontent.com/7545075/182042217-117fa2d8-538e-46a5-8e28-9c768730224c.png">

Ty! 💜

**Comment by matthewp** [comment]
Oh, I like this idea a lot! Yeah, it just exists to do `el.closest(selector)` to find the nearest ancestor with the prop. I think your idea could work, and would be nicer to look at and likely even fix #155 since we have to try and make the vars be valid attribute names.

I would want to add a benchmark first (something that's needed anyways). This is a part of the code that runs fairly frequently and I'm not sure what the perf of =~ is. But assuming it's acceptable, I like this change a lot.

**Comment by matthewp** [comment]
I'm prototyping this.

**Comment by matthewp** [comment]
I worked on this and couldn't see a perf difference so I'm going to implement it.

Since stores and item/index use a lot of the same code I'm going to need to refactor them to use this sort of method as well. It will probably be something like `data-corset-props`, `data-corset-stores` and `data-corset-scope` to represent each of these concepts, so a max of 3 corset attributes on an element if you happen to use all of these features on the same element.

**Comment by JaneOri** [comment]
awesome, thank you so much

Corset is awesome, really enjoy using it

**Comment by matthewp** [comment]
Released in https://github.com/matthewp/corset/releases/tag/v2.1.0
